[phases.setup]
nixPkgs = ["ruby_3_2", "libyaml", "libffi"]

[phases.install]
cmds = ["bundle install"]

[phases.build]
cmds = [
  "bundle exec rails tailwindcss:build",
  "bundle exec rails assets:precompile",
  "bundle exec rails db:migrate",
  "bundle exec rails db:seed"
]

[start]
cmd = "bundle exec rails server -p $PORT -e production"
